sudo: false
language: go
os: linux

go:
  - tip
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"

git:
  depth: 5
  submodules: false

branches:
  only:
    - master

install:
  - ./install.py --prefix ${GOPATH}

script:
  - ./test.sh
