sudo: false
language: go
os: linux

go:
  - tip
  - "1.11.x"
  - "1.10.x"

git:
  depth: 3
  submodules: false

branches:
  only:
    - master

install:
  - ./vendor/deps.sh
  - ./install.py --prefix ${PWD}/prefix

script:
  - ./test.sh
