# https://www.appveyor.com/docs/appveyor-yml/

version: build{build}

branches:
  only:
    - master

max_jobs: 3

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/jrmsdev/sadm
clone_depth: 3

stack: go 1.11

matrix:
  fast_finish: true

deploy: off

install:
  - ./vendor/deps.sh

before_build:
  - export GOPATH=/usr/go
  - go version

build_script:
  - ./install.py --prefix ${PWD}/prefix
  - mkdir build
  - tar -vcJf build/sadm-build${APPVEYOR_BUILD_NUMBER}.txz -C prefix .

test_script:
  - ./test.sh

artifacts:
  - path: 'build/sadm-build*.txz'
